#version 330

//$IF LIGHTS
struct Light{
    vec3 color;
};
//$ELSE
struct Light{
    vec3 color;
    float falloff;
};
//$END_IF

//$IF MATERIALS
struct Materials{
    vec3 color;
    float diffuse;
};
//$ELSE
struct Materials{
    vec3 color;
    float falloff;
    float falloff2;
};
//$END_IF


void main(){
    //$IF LIGHTS
    vec3 test;
    //$ELSE
    vec3 test4;
    //$END_IF
    //$IF MATERIALS
    vec3 test2;
    vec3 test3;
    //$END_IF
}